### ISSUE TITLE
Very slow execution of unit tests and bloated binary size with static_number

### ISSUE THREAD

**Issue by elcojacobs** [johnmcfarlane/cnl#447] opened 2019-05-15 16:31 UTC
Hi John,

Thanks for fixing #429!
I just merged develop and unit tests pass, but they are incredibly slow to run.
I have not figured out the exact cause yet.

Running gcc 8.3.0 with these arguments for unit test builds:
```
g++ -g -I/home/elco/repos/firmware/lib/inc -I/home/elco/repos/firmware/platform -I. -ffunction-sections -Wall -Werror=deprecated-declarations -MD -MP -MF build/test/lib/test/cnl_bloat_test.o.d -DDEBUG_BUILD -D_SYS_WAIT_H_ -D_SYS_WAIT_H -pthread -g -fprofile-arcs -ftest-coverage -Wno-system-headers -DPLATFORM_ID=3 -isystem /home/elco/opt/boost/boost_1_65_0 -std=gnu++14 -c -o build/test/lib/test/cnl_bloat_test.o /home/elco/repos/firmware/lib/test/cnl_bloat_test.cpp
```

The code changes can be seen here:
https://github.com/BrewBlox/brewblox-firmware/pull/69/files#diff-c1737f314e443320c64aa66a367ed7d1
Builds here:
https://dev.azure.com/brewblox/brewblox/_build?definitionId=10&_a=summary

I use static_number now and updated the CNL submodule.

Compared to the code before the PR:
 - The embedded binary increases from 101924 to 117380.
 - The run time of the unit tests went from 38 seconds to 4 min 26s.

Is this just the cause of rounding changes?
I'll try profiling the tests and update this issue.

**Comment by elcojacobs** [comment] 2019-05-15 17:11
Profile of this test:
https://github.com/elcojacobs/brewblox-firmware/blob/feature/cnl-update/lib/test/FixedPoint_test.cpp

Profiled with valgrind using:
```
valgrind --tool=callgrind lib_test_runner [fixedpoint]
sudo apt-get install valgrind kcachegrind graphviz
```

Output:

[callgrind.out.zip](https://github.com/johnmcfarlane/cnl/files/3183654/callgrind.out.zip)

Open with kcachegrind.

to_chars takes up 51%. Perhaps some side effect of catch tests. But at least it was a lot lighter before.

**Comment by johnmcfarlane** [comment] 2019-05-15 22:44
> Is this just the cause of rounding changes?

It's possibly because of changes related to this fix, yes. You don't appear to have inlining enabled which is likely to heavily affect performance: there are about five levels of arithmetic operators and their supporting functions between the outer type and the native integers backing them. It's inlining which reduces this down to (ideally) close to integer performance. 

Other than that, you may find you don't need all five of those layers. Given you're not performing rounding and assuming you don't require multi-word types, you may be able to get by with:

```c++
template<
        int Digits,
        int Exponent>
using saturated_elastic_fixed_point = cnl::fixed_point<
        cnl::overflow_integer<
                cnl::elastic_integer<
                        Digits,
                        int>,
                cnl::saturated_overflow_tag>,
        Exponent>;
```

Alternatively, there may legitimately be a performance regression that doesn't accompany additional functionality. I've not embarked on optimizing the deeply nested types yet as I'm still concentrating on correctness issues. Furthermore, `to_chars` is an especially demanding function which can probably be optimized a lot more and is missing a bunch of edge cases too.

**Comment by johnmcfarlane** [comment] 2019-05-23 21:51
@elcojacobs I've merged a change which might affect your bloat test either way (but hopefully for the better). It rearranges the nesting of the components in static_integer. Please let me know if it breaks anything or changes runtime performance.

**Closed** 2019-06-03 10:39 UTC

**Comment by elcojacobs** [comment] 2019-06-21 20:09
Hi John, sorry only just had time to look at your latest develop branch.

I'm now getting a lot of compilation errors when mixing types of different precision, is this a change in design and should I cast to a common type myself before arithmetic operations?

See godbolt for my unit tests that fail to compile:

https://godbolt.org/z/CA5DWF

```c
/opt/compiler-explorer/libs/cnl/include/cnl/_impl/../elastic_integer.h:333:36: error: call to function 'cast_to_common_type' that is neither visible in the template definition nor found by argument-dependent lookup
```
