### ISSUE TITLE
Changing default install path for CNL

### ISSUE THREAD

**Issue by priyankaankolekar** [johnmcfarlane/cnl#619] opened 2020-06-05 12:34 UTC
Hi John
I recently started using your library. It works magically on my local machine. When I migrate the code to a server, unfortunately I do not have write permissions to /usr/local/include/, so I have to install it at some other location, say /data/shared/common/cnl/.

On my local machine, the code works as expected. On the server, it is throwing errors like this one:

```sh
from <some_path>/src/main.cpp:16:
/data/home/ankoleka/.conan/data/cnl/0.0.2/johnmcfarlane/development/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/cnl/_impl/../_impl/wide_integer/../duplex_integer/multiply.h: In member function ‘constexpr cnl::_impl::long_multiply<T>::result_type<Lhs, Rhs> cnl::_impl::long_multiply<T>::operator()(const Lhs&, const Rhs&) const’:
/data/home/ankoleka/.conan/data/cnl/0.0.2/johnmcfarlane/development/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/cnl/_impl/../_impl/wide_integer/../duplex_integer/multiply.h:55:58: error: declaration of ‘using result_type = cnl::_impl::long_multiply<T>::result_type<Lhs, Rhs>’ shadows a member of 'this' [-Werror=shadow]
                 using result_type = result_type<Lhs, Rhs>;
```

I suspect it may be because of the library install path since that is the only thing different between my local machine and the server, but I am not entirely certain.

I am new to using conan, so I do not know where to even start looking. Do you have any suggestions/recommendations?

Thanks
Priyanka.

**Comment by johnmcfarlane** [comment] 2020-06-05 20:51
Hi Priyanka,
Thanks for bringing this to my attention.
It looks like on your server, you have the shadow and warnings-as-errors flags enabled. CNL won't compile with this combination of flags, something I will have to fix. If you're able, you can work around this problem by removing either the `-Werror` or `-Wshadow` flag. However, that's not a recommended solution in the long-run.

**Comment by priyankaankolekar** [comment] 2020-06-05 22:24
Hi John,
Thanks for your quick response.
Yes, you are right the warnings as errors flag is enabled. But what I
confounds me is that these are enabled on my local machine as well where
the project builds without any issues.

Like I mentioned, the only thing different (or so I think) is the install
location of the library on both entities.

But I will try without the flags and see if that works for now.

Thanks again for writing a very useful library. I hope it becomes part of
C++ like STL is.

Priyanka.

**Comment by johnmcfarlane** [comment] 2020-06-05 22:59
Thanks!

I've applied a potential fix. I'd be grateful to know whether it fixed your problem.

Are you saying that the library is installed under /usr locally where there's no problem but under /home on the server? If a header is found in a system search path (e.g. when specified by `-isystem`), then warnings are not emitted for that header. Try installing to a local directory locally and see if the warnings return.

**Comment by priyankaankolekar** [comment] 2020-06-10 11:24
Hi John,
Sorry for not getting back sooner.

Just to give you an idea of how I am building/installing the library (like I mentioned earlier, I am new to using conan and do not entirely understand it. I realized installing it on the server was proving to be quite a task with permission issues etc.):

<In /path/to/some/project/>
```sh
mkdir build
cd build
conan remote add johnmcfarlane/cnl https://api.bintray.com/conan/johnmcfarlane/cnl
conan install --build cnl ..
cmake ..
make
```
Does this look right to you? I am pretty darn sure I am missing/messing something, because I continue to see the issue with `-Wshadow` related error.

Also - do you mind updating the README/Installation instructions? I managed to use some hybrid from the README in this repo, and the README in the cnl_example repo.

**Comment by priyankaankolekar** [comment] 2020-06-12 10:54
Hi John,
Do you have to separately update the conan package with these updates you applied to take care of the warnings?
Thanks,
Priyanka.

**Comment by johnmcfarlane** [comment] 2020-06-13 10:15
Sorry, yes, that conan package version was out of date. I added a version 0.0.3/development with the fix.

I followed the instructions in the README and was not able to find a snag. Can you tell me which step was a problem and/or what error messages/problems you're seeing?

**Comment by priyankaankolekar** [comment] 2020-06-16 17:32
Hi John,
Thanks so much for updating the conan package. I am having some trouble getting updated version to build. I have tried both 0.0.3 and 0.0.4.

Here is what i see:
```sh
ankoleka@a483e7b9d582 build (ankoleka_dev)$ conan install --build cnl ..
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libstdc++11
compiler.version=11.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

cnl/0.0.3@johnmcfarlane/development: Not found in local cache, looking in remotes...
cnl/0.0.3@johnmcfarlane/development: Trying with 'conan-center'...
cnl/0.0.3@johnmcfarlane/development: Trying with 'johnmcfarlane/cnl'...
Downloading conanmanifest.txt completed [0.06k]                                          
Downloading conanfile.py completed [0.91k]                                               
cnl/0.0.3@johnmcfarlane/development: Downloaded recipe revision 0
benchmark/1.5.0@johnmcfarlane/stable: WARN: Package is corrupted, removing folder: /Users/ankoleka/.conan/data/benchmark/1.5.0/johnmcfarlane/stable/package/ebb103f769d6a6b15f941f0d31abaf0641053211
cnl/0.0.3@johnmcfarlane/development: Forced build from source
conanfile.txt: Installing package
Requirements
    benchmark/1.5.0@johnmcfarlane/stable from local cache - Cache
    cnl/0.0.3@johnmcfarlane/development from 'johnmcfarlane/cnl' - Downloaded
    gtest/1.10.0 from 'conan-center' - Cache
Packages
    benchmark/1.5.0@johnmcfarlane/stable:ebb103f769d6a6b15f941f0d31abaf0641053211 - Missing
    cnl/0.0.3@johnmcfarlane/development:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Build
    gtest/1.10.0:9c77c8e9c698f5cb54065de5b7cf579ce2a48699 - Missing

Installing (downloading, building) binaries...
ERROR: Missing binary: benchmark/1.5.0@johnmcfarlane/stable:ebb103f769d6a6b15f941f0d31abaf0641053211
ERROR: Missing binary: gtest/1.10.0:9c77c8e9c698f5cb54065de5b7cf579ce2a48699

benchmark/1.5.0@johnmcfarlane/stable: WARN: Can't find a 'benchmark/1.5.0@johnmcfarlane/stable' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=apple-clang, compiler.libcxx=libstdc++11, compiler.version=11.0, os=Macos
- Options: enable_exceptions=True, enable_lto=False, fPIC=True, shared=False
- Dependencies: 
- Requirements: 
- Package ID: ebb103f769d6a6b15f941f0d31abaf0641053211

ERROR: Missing prebuilt package for 'benchmark/1.5.0@johnmcfarlane/stable'
Try to build it from sources with "--build benchmark"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
```

**Comment by johnmcfarlane** [comment] 2020-06-16 19:36
The install command has changed. I've updated the . Try `conan install --build missing ..`. Also, you may find the [cnl_example](https://github.com/johnmcfarlane/cnl_example) project helpful. It's a very simple example of how you might use the CNL library as a dependency in another project.

**Comment by priyankaankolekar** [comment] 2020-06-17 12:21
Thank you so much for patiently answering all my questions. I have learnt a lot of new things through this exercise. And like I mentioned before, the CNL library has made integrating fixed point arithmetic very easy. I build software to simulate hardware systems, so fixed point is very crucial. CNL is just what I needed.

**Comment by johnmcfarlane** [comment] 2020-06-17 14:51
You're welcome. Feedback from users is essential to successful software so
thank you.

**Comment by priyankaankolekar** [comment] 2020-06-23 04:17
Hi John,

The changes in the conan package version 0.0.4 work absolutely fine on Linux. When I try the same setup on Mac it fails with this:
```
conan install --build missing ..
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libstdc++11
compiler.version=11.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

benchmark/1.5.0@johnmcfarlane/stable: WARN: Package is corrupted, removing folder: /Users/ankoleka/.conan/data/benchmark/1.5.0/johnmcfarlane/stable/package/ebb103f769d6a6b15f941f0d31abaf0641053211
conanfile.txt: Installing package
Requirements
    benchmark/1.5.0@johnmcfarlane/stable from local cache - Cache
    cnl/0.0.3@johnmcfarlane/development from 'johnmcfarlane/cnl' - Cache
    gtest/1.10.0 from 'conan-center' - Cache
Packages
    benchmark/1.5.0@johnmcfarlane/stable:ebb103f769d6a6b15f941f0d31abaf0641053211 - Build
    cnl/0.0.3@johnmcfarlane/development:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Build
    gtest/1.10.0:9c77c8e9c698f5cb54065de5b7cf579ce2a48699 - Build

Installing (downloading, building) binaries...
benchmark/1.5.0@johnmcfarlane/stable: WARN: Build folder is dirty, removing it: /Users/ankoleka/.conan/data/benchmark/1.5.0/johnmcfarlane/stable/build/ebb103f769d6a6b15f941f0d31abaf0641053211
benchmark/1.5.0@johnmcfarlane/stable: Copying sources to build folder
benchmark/1.5.0@johnmcfarlane/stable: Building your package in /Users/ankoleka/.conan/data/benchmark/1.5.0/johnmcfarlane/stable/build/ebb103f769d6a6b15f941f0d31abaf0641053211
benchmark/1.5.0@johnmcfarlane/stable: Generator cmake created conanbuildinfo.cmake
benchmark/1.5.0@johnmcfarlane/stable: Calling build()
-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: called by CMake conan helper
-- Conan: called inside local cache
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Conan: Adjusting fPIC flag (ON)
-- Conan: C++ stdlib: libstdc++11
-- Failed to find LLVM FileCheck
-- Found Git: /usr/local/bin/git (found version "2.25.0") 
-- git Version: v0.0.0
-- Version: 0.0.0
-- Performing Test HAVE_CXX_FLAG_STD_CXX11
-- Performing Test HAVE_CXX_FLAG_STD_CXX11 - Failed
-- Performing Test HAVE_CXX_FLAG_STD_CXX0X
-- Performing Test HAVE_CXX_FLAG_STD_CXX0X - Failed
-- Performing Test HAVE_CXX_FLAG_WALL
-- Performing Test HAVE_CXX_FLAG_WALL - Failed
-- Performing Test HAVE_CXX_FLAG_WEXTRA
-- Performing Test HAVE_CXX_FLAG_WEXTRA - Failed
-- Performing Test HAVE_CXX_FLAG_WSHADOW
-- Performing Test HAVE_CXX_FLAG_WSHADOW - Failed
-- Performing Test HAVE_CXX_FLAG_WERROR
-- Performing Test HAVE_CXX_FLAG_WERROR - Failed
-- Performing Test HAVE_CXX_FLAG_PEDANTIC
-- Performing Test HAVE_CXX_FLAG_PEDANTIC - Failed
-- Performing Test HAVE_CXX_FLAG_PEDANTIC_ERRORS
-- Performing Test HAVE_CXX_FLAG_PEDANTIC_ERRORS - Failed
-- Performing Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32
-- Performing Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32 - Failed
-- Performing Test HAVE_CXX_FLAG_FSTRICT_ALIASING
-- Performing Test HAVE_CXX_FLAG_FSTRICT_ALIASING - Failed
-- Performing Test HAVE_CXX_FLAG_WNO_DEPRECATED_DECLARATIONS
-- Performing Test HAVE_CXX_FLAG_WNO_DEPRECATED_DECLARATIONS - Failed
-- Performing Test HAVE_CXX_FLAG_WNO_DEPRECATED
-- Performing Test HAVE_CXX_FLAG_WNO_DEPRECATED - Failed
-- Performing Test HAVE_CXX_FLAG_WD654
-- Performing Test HAVE_CXX_FLAG_WD654 - Failed
-- Performing Test HAVE_CXX_FLAG_WTHREAD_SAFETY
-- Performing Test HAVE_CXX_FLAG_WTHREAD_SAFETY - Failed
-- Performing Test HAVE_CXX_FLAG_COVERAGE
-- Performing Test HAVE_CXX_FLAG_COVERAGE - Failed
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK -- failed to compile
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY


-- Build files have been written to: /Users/ankoleka/.conan/data/benchmark/1.5.0/johnmcfarlane/stable/build/ebb103f769d6a6b15f941f0d31abaf0641053211
Scanning dependencies of target benchmark
[  4%] Building CXX object src/CMakeFiles/benchmark.dir/benchmark_api_internal.cc.o
[  9%] Building CXX object src/CMakeFiles/benchmark.dir/benchmark.cc.o
[ 14%] Building CXX object src/CMakeFiles/benchmark.dir/benchmark_name.cc.o
[ 19%] Building CXX object src/CMakeFiles/benchmark.dir/benchmark_register.cc.o
[ 23%] Building CXX object src/CMakeFiles/benchmark.dir/benchmark_runner.cc.o
[ 28%] Building CXX object src/CMakeFiles/benchmark.dir/colorprint.cc.o
[ 33%] Building CXX object src/CMakeFiles/benchmark.dir/commandlineflags.cc.o
[ 38%] Building CXX object src/CMakeFiles/benchmark.dir/complexity.cc.o
warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from /Users/ankoleka/.conan/data/benchmark/1.5.0/johnmcfarlane/stable/build/ebb103f769d6a6b15f941f0d31abaf0641053211/src/benchmark_name.cc:15:
/Users/ankoleka/.conan/data/benchmark/1.5.0/johnmcfarlane/stable/build/ebb103f769d6a6b15f941f0d31abaf0641053211/include/benchmark/benchmark.h:172:10: fatal error: 'algorithm' file not found
#include <algorithm>
         ^~~~~~~~~~~In file included from /Users/ankoleka/.conan/data/benchmark/1.5.0/johnmcfarlane/stable/build/ebb103f769d6a6b15f941f0d31abaf0641053211/src/benchmark_api_internal.cc:
1:
In file included from /Users/ankoleka/.conan/data/benchmark/1.5.0/johnmcfarlane/stable/build/ebb103f769d6a6b15f941f0d31abaf0641053211/src/benchmark_api_internal.h:4:
/Users/ankoleka/.conan/data/benchmark/1.5.0/johnmcfarlane/stable/build/ebb103f769d6a6b15f941f0d31abaf0641053211/include/benchmark/benchmark.h:172:10: fatal error: 'algorithm' file not found
#include <algorithm>
         ^~~~~~~~~~~
warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from /Users/ankoleka/.conan/data/benchmark/1.5.0/johnmcfarlane/stable/build/ebb103f769d6a6b15f941f0d31abaf0641053211/src/commandlineflags.cc:15:
/Users/ankoleka/.conan/data/benchmark/1.5.0/johnmcfarlane/stable/build/ebb103f769d6a6b15f941f0d31abaf0641053211/src/commandlineflags.h:4:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^~~~~~~~~
1 warning and 1 error generated.
make[2]: *** [src/CMakeFiles/benchmark.dir/commandlineflags.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 warning and 1 error generated.
1 warning and 1 error generated.
make[2]: *** [src/CMakeFiles/benchmark.dir/benchmark_api_internal.cc.o] Error 1
make[2]: *** [src/CMakeFiles/benchmark.dir/benchmark_name.cc.o] Error 1
warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from /Users/ankoleka/.conan/data/benchmark/1.5.0/johnmcfarlane/stable/build/ebb103f769d6a6b15f941f0d31abaf0641053211/src/benchmark_register.cc:15:
/Users/ankoleka/.conan/data/benchmark/1.5.0/johnmcfarlane/stable/build/ebb103f769d6a6b15f941f0d31abaf0641053211/src/benchmark_register.h:4:10: fatal error: 'vector' file not found
#include <vector>
         ^~~~~~~~
warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from /Users/ankoleka/.conan/data/benchmark/1.5.0/johnmcfarlane/stable/build/ebb103f769d6a6b15f941f0d31abaf0641053211/src/benchmark.cc:15:
/Users/ankoleka/.conan/data/benchmark/1.5.0/johnmcfarlane/stable/build/ebb103f769d6a6b15f941f0d31abaf0641053211/include/benchmark/benchmark.h:172:10: fatal error: 'algorithm' file not found
#include <algorithm>
         ^~~~~~~~~~~
In file included from /Users/ankoleka/.conan/data/benchmark/1.5.0/johnmcfarlane/stable/build/ebb103f769d6a6b15f941f0d31abaf0641053211/src/benchmark_runner.cc:15:
In file included from /Users/ankoleka/.conan/data/benchmark/1.5.0/johnmcfarlane/stable/build/ebb103f769d6a6b15f941f0d31abaf0641053211/src/benchmark_runner.h:18:
In file included from /Users/ankoleka/.conan/data/benchmark/1.5.0/johnmcfarlane/stable/build/ebb103f769d6a6b15f941f0d31abaf0641053211/src/benchmark_api_internal.h:4:
/Users/ankoleka/.conan/data/benchmark/1.5.0/johnmcfarlane/stable/build/ebb103f769d6a6b15f941f0d31abaf0641053211/include/benchmark/benchmark.h:172:10: fatal error: 'algorithm' file not found
#include <algorithm>
         ^~~~~~~~~~~
warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from /Users/ankoleka/.conan/data/benchmark/1.5.0/johnmcfarlane/stable/build/ebb103f769d6a6b15f941f0d31abaf0641053211/src/colorprint.cc:15:
/Users/ankoleka/.conan/data/benchmark/1.5.0/johnmcfarlane/stable/build/ebb103f769d6a6b15f941f0d31abaf0641053211/src/colorprint.h:4:10: fatal error: 'cstdarg' file not found
#include <cstdarg>
         ^~~~~~~~~
In file included from /Users/ankoleka/.conan/data/benchmark/1.5.0/johnmcfarlane/stable/build/ebb103f769d6a6b15f941f0d31abaf0641053211/src/complexity.cc:18:
/Users/ankoleka/.conan/data/benchmark/1.5.0/johnmcfarlane/stable/build/ebb103f769d6a6b15f941f0d31abaf0641053211/include/benchmark/benchmark.h:172:10: fatal error: 'algorithm' file not found
#include <algorithm>
         ^~~~~~~~~~~
1 warning and 1 error generated.
make[2]: *** [src/CMakeFiles/benchmark.dir/complexity.cc.o] Error 1
1 warning and 1 error generated.
1 warning and 1 error generated.
1 warning and 1 error generated.
1 warning and 1 error generated.
make[2]: *** [src/CMakeFiles/benchmark.dir/colorprint.cc.o] Error 1
make[2]: *** [src/CMakeFiles/benchmark.dir/benchmark.cc.o] Error 1
make[2]: *** [src/CMakeFiles/benchmark.dir/benchmark_runner.cc.o] Error 1
make[2]: *** [src/CMakeFiles/benchmark.dir/benchmark_register.cc.o] Error 1
make[1]: *** [src/CMakeFiles/benchmark.dir/all] Error 2
make: *** [all] Error 2
benchmark/1.5.0@johnmcfarlane/stable: 
benchmark/1.5.0@johnmcfarlane/stable: ERROR: Package 'ebb103f769d6a6b15f941f0d31abaf0641053211' build failed
benchmark/1.5.0@johnmcfarlane/stable: WARN: Build folder /Users/ankoleka/.conan/data/benchmark/1.5.0/johnmcfarlane/stable/build/ebb103f769d6a6b15f941f0d31abaf0641053211
ERROR: benchmark/1.5.0@johnmcfarlane/stable: Error in build() method, line 68
	cmake.build()
	ConanException: Error 2 while executing cmake --build '/Users/ankoleka/.conan/data/benchmark/1.5.0/johnmcfarlane/stable/build/ebb103f769d6a6b15f941f0d31abaf0641053211/.' '--' '-j8'
```

Would you mind taking a look?
Thanks
Priyanka.

**Comment by hbe72** [comment] 2020-06-25 10:10
For all Clang variants I need to edit the test/cmake/common.cmake immediately after first line as follows:
```cpp
include(ExternalProject)
include(cmake/toolchain/clang.cmake)
```
Thus the compiler specific options have to be included.

In OSX I can not use libstdc++11 with Clang compiler. Not with apple-clang or with llvm clang. The errors you are experiencing are due to mismatch between standard headers and libraries.

For apple-clang compilation the conan profile should be as follows. For me this is the default profile on Mac:
```cpp
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=11.0
compiler.libcxx=libc++
compiler.cppstd=14
build_type=Release
[options]
[build_requires]
[env]
```

Then for clang-10, which you can get from homebrew (brew install llvm). I call this clang-10 profile on Mac:
```cpp
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=10
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
CC=/usr/local/opt/llvm/bin/clang
CXX=/usr/local/opt/llvm/bin/clang++
```

Then build and install the conan dependencies to your project as:
```cpp
$ conan install --build=missing --profile=<profile-you-want-to-use> <path_to_cnl_project>
```
Depending which compiler (profile) I want to use.

In all platforms if you are using anything else than default compiler you have to set the CC and CXX environment variables accordingly as conan profile only controls the compilation of conan packages. Not CNL.
```cpp
$ export CC=/usr/local/opt/llvm/bin/clang
$ export CXX=/usr/local/opt/llvm/bin/clang++
```

And then configure:
```cpp
$ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=14 -DCNL_SANITIZE=OFF -DCMAKE_PROJECT_cnl_INCLUDE:FILEPATH="$(pwd)"/conan_paths.cmake <path_to_cnl_project>
```
Notice that for all Clang variants For all Clang variants I need to turn the CNL_SANITIZE=OFF. CXX_STANDARD=17 will issue some errors due to deprecated features.

Naturally install directory can be changed wherever you want it by passing -DCMAKE_INSTALL_PREFIX=some-directory-path in the previous configuration step.

And more: 
gcc-9 profile on mac and gcc-9 installed from homebrew:
```cpp
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
CC=/usr/local/bin/gcc-9
CXX=/usr/local/bin/g++-9
```

clang-10 profile on Linux
```cpp
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=10
compiler.libcxx=libstdc++11
compiler.cppstd=14
build_type=Release
[options]
[build_requires]
[env]
CC=/usr/bin/clang-10
CXX=/usr/bin/clang++-10
```

Thus the correct steps are:
```cpp
$ git clone https://github.com/johnmcfarlane/cnl.git
$ cd cnl
$ mkdir cmake-build-clang
$ cd cmake-build-clang
$ conan install --build=missing --profile=default ..
$ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PROJECT_cnl_INCLUDE:FILEPATH="$(pwd)"/conan_paths.cmake ..
$ cmake --build . --target test-all
$ ctest -R test-unit
```

If you experience compilation errors... start from scratch
```cpp
$ rm -rf *
$ conan remove gtest/1.10.0
$ conan remove benchmark/1.5.0
$ conan install --build=missing --profile=default ..
```
Hope this helps.

And finally. Conan profiles can be edited manually in .conan/profiles directory.

**Comment by johnmcfarlane** [comment] 2020-06-29 21:02
@priyankaankolekar do @hbe72's notes help at all? Also, I noticed in the [README.md](https://github.com/johnmcfarlane/cnl/blob/0040322323c1d75097ee26eb26a45689e7958854/README.md) that there is a command in the instructions which might not apply to OS X: 

```bash
conan profile update settings.compiler.libcxx=libstdc++11 default
```

If you are following this line, you might end up with the wrong standard library. I've really no idea. Just a thought.

Also, while I don't have access to OS X hardware, if you can produce an exhaustive list of repo steps, I can maybe reproduce this in Travis-CI.

**Comment by priyankaankolekar** [comment] 2020-07-02 09:06
Thank you @hbe72. These instructions worked.
@johnmcfarlane - thank you for updating the README.

**Comment by johnmcfarlane** [comment] 2020-07-02 10:02
@priyankaankolekar you are welcome. I'll close this issue now. Note that 0.0.6 is now the latest release.

**Closed** 2020-07-02 10:02 UTC
