### ISSUE TITLE
v1.1.7 crash after multiplication

### ISSUE THREAD

**Issue by rezeptemensch** [johnmcfarlane/cnl#914] opened 2021-07-25 12:50 UTC
**Describe the bug:**

Executables crash when trying to output values on std out after multiplication.

**To Reproduce:**

```c++
auto foo = scaled_integer<int32_t, power<-30>>{0.01} * scaled_integer<int32_t, power<-30>>{0.01};
std::cout << foo << std::endl;
```

This crashes:
```
digit[0]<10
terminate called without an active exception
```

**Expected behavior:**

No crash and output on std out.

**Desktop (please complete the following information):**

* OS: [e.g. iOS]: Debian 5.10.40-1 (2021-05-28) x86_64 GNU/Linux
* Compiler version:  gcc version 10.2.1 20210110 (Debian 10.2.1-6) 
* Compiler flags used: -DX86DEBUG -g -Wall -Wpedantic -std=gnu++17
* CMake version: 3.18.4
* Conan version: -
* CNL version (or Git branch/SHA): v1.1.7

**Link to Compiler Explorer:**

[Crashing example on v1.1.5](https://godbolt.org/z/sMrqrdnKx).

**Comment by johnmcfarlane** [comment] 2021-07-25 20:26
Hi. 

Firstly, the multiplication overflows. You multiply two 32-bit numbers each with underlying integer values, `0.01 * 2^30`, which is `10,737,418`. `10,737,418 * 10,737,418` is `115,292,145,306,724`, which is wider than a 32-bit integer, hence the overflow. You can see that if you enable UBSan (with `-fsanitize=undefined`) or make the calculation a constant expression. ([example](https://godbolt.org/z/3d7bGcGvG))

To avoid the overflow, use a 64-bit integer for the multiplication. ([example](https://godbolt.org/z/K7Wc4PjfT)), ([faq](https://johnmcfarlane.github.io/cnl/index.html#overflow))

However, the crash isn't caused by the multiplication, but by the text conversion in the streaming operator. I believe that's a duplicate of #486 which is fixed at head.

**Closed** 2022-01-08 07:55 UTC
Labels: bug
