### ISSUE TITLE
Compilation issue when including CNL with Boost

### ISSUE THREAD

**Issue by Hyvok** [johnmcfarlane/cnl#548] opened 2020-01-27 17:30 UTC
Hello!

I've recently tried to integrate CNL to my project but I have issues compiling it in combination with some Boost 1.72.0 libraries. I am using MSVC 19.24.28315.0 (Visual Studio 2019) and I did try to use some older MSVC too without success.

The most simplified example I can create is an empty Main.cpp, which I can compile with the command: cl /std:c++17 -IC:\local\boost_1_72_0 -I..\inc\cnl\include ..\Main.cpp

```
#include "boost/program_options/detail/value_semantic.hpp"
//#include <boost/program_options/options_description.hpp>
#include <cnl/all.h>

int main()
{
    return 1;
}
```

The top most "value_semantic.hpp" file is the file I end up with if I start following the include tree from the "options_description.hpp" file which seems to trigger issues by itself. If I include either one I get the following type compilation errors from CNL:

```
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl\scaled_integer\to_chars.h(116): error C2059: syntax error: '{'
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl\scaled_integer\to_chars.h(116): error C2143: syntax error: missing ';' before '{'
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl\scaled_integer\to_chars.h(118): error C2059: syntax error: ')'
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl\scaled_integer\to_chars.h(122): error C2143: syntax error: missing ';' before '{'
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl\scaled_integer\to_chars.h(123): error C2947: expecting '>' to terminate template-argument-list, found '>='
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl\scaled_integer\to_chars.h(123): error C2988: unrecognizable template declaration/definition
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl\scaled_integer\to_chars.h(123): error C2059: syntax error: '='
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl\scaled_integer\to_chars.h(123): error C2059: syntax error: ')'
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl\scaled_integer\to_chars.h(123): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl\scaled_integer\to_chars.h(123): error C2365: 'cnl::_impl::terminate': redefinition; previous definition was 'function'
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl\terminate.h(18): note: see declaration of 'cnl::_impl::terminate'
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl\scaled_integer\to_chars.h(123): error C2513: 'cnl::_impl::terminate': no variable declared before '='
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl\scaled_integer\to_chars.h(126): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl\scaled_integer\to_chars.h(128): error C2988: unrecognizable template declaration/definition
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl\scaled_integer\to_chars.h(128): error C2059: syntax error: 'for'
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl\scaled_integer\to_chars.h(128): error C2065: 'Rep': undeclared identifier
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl\scaled_integer\to_chars.h(128): error C2065: 'Exponent': undeclared identifier
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl\scaled_integer\to_chars.h(128): error C2065: 'Radix': undeclared identifier
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl\scaled_integer\to_chars.h(128): error C2975: 'Exponent': invalid template argument for 'cnl::power', expected compile-time constant expression
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl\scaled\definition.h(15): note: see declaration of 'Exponent'
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl\scaled_integer\to_chars.h(128): error C2975: 'Radix': invalid template argument for 'cnl::power', expected compile-time constant expression
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl\scaled\definition.h(15): note: see declaration of 'Radix'
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl\scaled_integer\to_chars.h(128): error C2923: 'cnl::scaled_integer': 'Rep' is not a valid template type argument for parameter 'Rep'
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl\scaled_integer\to_chars.h(128): error C2143: syntax error: missing ';' before '{'
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl\scaled_integer\to_chars.h(128): error C2143: syntax error: missing ')' before ';'
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl\scaled_integer\to_chars.h(128): error C2447: '{': missing function header (old-style formal list?)
```
And so forth. If I change the include order in the main I get errors from the boost file. If I remove either include it compiles fine.

I'm somewhat puzzled by this issue and cannot see anything obviously wrong. Any ideas what could be the culprit?

**Comment by johnmcfarlane** [comment] 2020-01-27 23:31
Hello. Thanks for trying out CNL. I'm afraid that nothing springs to mind. That's an odd one. What do the errors look like when the header orders are switched? Also, does rearranging the `-I` switches have any effect?

Meanwhile, I'm just trying to reproduce in CI will see how that went in the morning.

**Comment by johnmcfarlane** [comment] 2020-01-28 05:29
This looks like a reproduction using Boost 1.66: https://ci.appveyor.com/project/johnmcfarlane/cnl/builds/30393320/job/p6pf2qux264hfduj

**Comment by Hyvok** [comment] 2020-01-28 05:47
Indeed it does!

Reverting the -I flag order between boost and CNL does not seem to make a difference.

If I revert the header include order the errors I get from boost look like:
```
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(16): error C2143: syntax error: missing ';' before 'std::string'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(16): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(20): error C2988: unrecognizable template declaration/definition
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(20): error C2143: syntax error: missing ';' before '<'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(20): error C2059: syntax error: '<'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(20): error C2039: 'name': is not a member of '`global namespace''
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(21): error C2143: syntax error: missing ';' before '{'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(21): error C2447: '{': missing function header (old-style formal list?)
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(38): error C2988: unrecognizable template declaration/definition
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(38): error C2143: syntax error: missing ';' before '<'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(38): error C2182: 'typed_value': illegal use of type 'void'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(38): error C2371: 'boost::program_options::typed_value': redefinition; different basic types
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(20): note: see declaration of 'boost::program_options::typed_value'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(38): error C2059: syntax error: '<'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(38): error C2039: 'notify': is not a member of '`global namespace''
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(38): error C2039: 'any': is not a member of 'boost'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(14): note: see declaration of 'boost'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(39): error C2143: syntax error: missing ';' before '{'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(39): error C2447: '{': missing function header (old-style formal list?)
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(57): error C2039: 'vector': is not a member of 'std'
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl/scaled_integer/extras.h(289): note: see declaration of 'std'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(57): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(57): error C2988: unrecognizable template declaration/definition
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(57): error C2143: syntax error: missing ',' before '<'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(72): error C2144: syntax error: 'void' should be preceded by ';'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(72): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(72): error C2039: 'any': is not a member of 'boost'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(14): note: see declaration of 'boost'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(72): error C2143: syntax error: missing ',' before '&'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(85): error C2039: 'any': is not a member of 'boost'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(14): note: see declaration of 'boost'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(85): error C2065: 'any': undeclared identifier
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(85): error C2065: 'v': undeclared identifier
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(86): error C2988: unrecognizable template declaration/definition
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(86): error C2059: syntax error: 'const'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(86): error C2039: 'vector': is not a member of 'std'
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl/scaled_integer/extras.h(289): note: see declaration of 'std'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(88): error C2143: syntax error: missing ';' before '{'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(88): error C2447: '{': missing function header (old-style formal list?)
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(99): error C2144: syntax error: 'void' should be preceded by ';'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(99): error C2039: 'any': is not a member of 'boost'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(14): note: see declaration of 'boost'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(99): error C2065: 'any': undeclared identifier
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(99): error C2065: 'v': undeclared identifier
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(100): error C2988: unrecognizable template declaration/definition
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(100): error C2059: syntax error: 'const'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(100): error C2039: 'vector': is not a member of 'std'
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl/scaled_integer/extras.h(289): note: see declaration of 'std'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(105): error C2144: syntax error: 'void' should be preceded by ';'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(105): error C2039: 'any': is not a member of 'boost'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(14): note: see declaration of 'boost'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(105): error C2065: 'any': undeclared identifier
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(105): error C2065: 'v': undeclared identifier
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(106): error C2988: unrecognizable template declaration/definition
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(106): error C2059: syntax error: 'const'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(106): error C2039: 'vector': is not a member of 'std'
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl/scaled_integer/extras.h(289): note: see declaration of 'std'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(114): error C2144: syntax error: 'void' should be preceded by ';'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(114): error C2039: 'any': is not a member of 'boost'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(14): note: see declaration of 'boost'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(114): error C2065: 'any': undeclared identifier
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(114): error C2065: 'v': undeclared identifier
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(115): error C2988: unrecognizable template declaration/definition
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(115): error C2059: syntax error: 'const'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(115): error C2039: 'vector': is not a member of 'std'
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl/scaled_integer/extras.h(289): note: see declaration of 'std'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(120): error C2144: syntax error: 'void' should be preceded by ';'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(120): error C2039: 'any': is not a member of 'boost'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(14): note: see declaration of 'boost'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(120): error C2065: 'any': undeclared identifier
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(120): error C2065: 'v': undeclared identifier
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(121): error C2988: unrecognizable template declaration/definition
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(121): error C2059: syntax error: 'const'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(121): error C2039: 'vector': is not a member of 'std'
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl/scaled_integer/extras.h(289): note: see declaration of 'std'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(130): error C2039: 'any': is not a member of 'boost'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(14): note: see declaration of 'boost'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(130): error C2065: 'any': undeclared identifier
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(130): error C2065: 'v': undeclared identifier
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(131): error C2988: unrecognizable template declaration/definition
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(131): error C2059: syntax error: 'const'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(131): error C2039: 'vector': is not a member of 'std'
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl/scaled_integer/extras.h(289): note: see declaration of 'std'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(132): error C2039: 'vector': is not a member of 'std'
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl/scaled_integer/extras.h(289): note: see declaration of 'std'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(134): error C2143: syntax error: missing ';' before '{'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(134): error C2447: '{': missing function header (old-style formal list?)
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(160): error C2039: 'any': is not a member of 'boost'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(14): note: see declaration of 'boost'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(160): error C2065: 'any': undeclared identifier
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(160): error C2065: 'v': undeclared identifier
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(161): error C2988: unrecognizable template declaration/definition
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(161): error C2059: syntax error: 'const'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(161): error C2039: 'vector': is not a member of 'std'
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl/scaled_integer/extras.h(289): note: see declaration of 'std'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(164): error C2143: syntax error: missing ';' before '{'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(164): error C2447: '{': missing function header (old-style formal list?)
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(174): error C2988: unrecognizable template declaration/definition
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(174): error C2143: syntax error: missing ';' before '<'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(174): error C2182: 'typed_value': illegal use of type 'void'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(174): error C2371: 'boost::program_options::typed_value': redefinition; different basic types
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(20): note: see declaration of 'boost::program_options::typed_value'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(174): error C2059: syntax error: '<'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(175): error C2039: 'xparse': is not a member of '`global namespace''
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(175): error C2039: 'any': is not a member of 'boost'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(14): note: see declaration of 'boost'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(176): error C2039: 'vector': is not a member of 'std'
c:\users\3504048\documents\projects\temp\inc\cnl\include\cnl\_impl/scaled_integer/extras.h(289): note: see declaration of 'std'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(176): error C2065: 'charT': undeclared identifier
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(176): error C2923: 'std::basic_string': 'charT' is not a valid template type argument for parameter '_Elem'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(176): error C3203: 'char_traits': unspecialized class template can't be used as a template argument for template parameter '_Traits', expected a real type
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(176): error C3203: 'allocator': unspecialized class template can't be used as a template argument for template parameter '_Alloc', expected a real type
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(177): error C2143: syntax error: missing ';' before '{'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(177): error C2447: '{': missing function header (old-style formal list?)
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(188): error C2988: unrecognizable template declaration/definition
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(188): error C2143: syntax error: missing ';' before '<'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(188): error C2059: syntax error: '<'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(190): error C2143: syntax error: missing ';' before '{'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(190): error C2447: '{': missing function header (old-style formal list?)
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(196): error C2988: unrecognizable template declaration/definition
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(196): error C2143: syntax error: missing ';' before '<'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(196): error C2059: syntax error: '<'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(198): error C2143: syntax error: missing ';' before '{'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(198): error C2447: '{': missing function header (old-style formal list?)
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(205): error C2988: unrecognizable template declaration/definition
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(205): error C2143: syntax error: missing ';' before '<'
C:\local\boost_1_72_0\boost/program_options/detail/value_semantic.hpp(205): fatal error C1003: error count exceeds 100; stopping compilation
```

**Comment by johnmcfarlane** [comment] 2020-01-28 06:12
I'm afraid including only a header from a *details* subfolder isn't going to reveal much as they may depend upon definitions in other headers. In this case, it's probably just missing the definition of macro, `BOOST_PROGRAM_OPTIONS_DECL`.

**Comment by Hyvok** [comment] 2020-01-28 06:26
If including the header "boost/program_options/options_description.hpp" after "all/cnl.h" then I get no compile errors.

**Comment by johnmcfarlane** [comment] 2020-01-28 18:12
It sounds like you're unblocked at least. Could you confirm that?

**Comment by Hyvok** [comment] 2020-01-28 19:28
Yep I can continue evaluating the library at least. Integrating in to my project would at least require me to change my standard include ordering of things in this case (I always include stl/boost/Qt etc. first and then smaller dependencies as a convention)...

**Comment by johnmcfarlane** [comment] 2020-01-29 19:33
Thanks. I certainly want to get to the bottom of any problem with CNL but have quite a backlog of issues to get through so need to prioritise blockers. I'll keep this issue open for now.

Let me know if you have any other issues or suggestions!

**Comment by johnmcfarlane** [comment] 2021-03-08 01:52
While making minor improvements to Boost integration in #771, I didn't notice anything untoward in this respect so I'm going to close this issue.

**Closed by johnmcfarlane** 2021-03-08 01:52 UTC
Labels: Windows, bug, request
