### ISSUE TITLE
Incorrect integer representation (rep) of static number and it's derivates

### ISSUE THREAD

**Issue by hbe72** [johnmcfarlane/cnl#849] opened 2021-04-08 06:55 UTC
**Describe the bug:**

With HEAD of main 

This should miscompile as _builtin_unreachable, instead this miscompiles as static_assert(identical(n_rep, 32767))
```cpp
    namespace static_number_rep_incorrect {
        static constexpr auto n = cnl::static_number<16, -15>{1.0};  
        static constexpr auto n_rep = (int32_t) to_rep(n);
        static_assert(identical(n_rep, 32767));
    }
```
The previous compiles correctly if 32767 is changed to 32768, but that is incorrect as largest signed integer represented by 16-bits is 32767.

This miscompiles as  static_assert(identical(n_rep, 32767))
```cpp
    namespace static_number_saturated_rep {
        static constexpr auto n = cnl::static_number<16,-15, cnl::neg_inf_rounding_tag, cnl::saturated_overflow_tag, int16_t>{1.0};
        static constexpr auto n_rep = (int32_t) to_rep(n);
        static_assert(identical(n_rep, 32767));
    }
```
Which is again incorrect as the 16-bits should saturate to 32767 (0.999969482421875).

It seems that underlying static_number type uses one additional integer bits as:

```cpp
    namespace static_number_saturated_rep_incorrect {
        static constexpr auto n = cnl::static_number<16,-15, cnl::neg_inf_rounding_tag, cnl::saturated_overflow_tag, int16_t>{2.0};
        static constexpr auto n_rep = (int32_t) to_rep(n);
        static_assert(identical(n_rep, 65535)); //Saturated to here
        static_assert(identical(n_rep, 32767)); //This should be the correct result
    }
```

**Desktop (please complete the following information):**
OS - OsX
Compiler - gcc-10 (Homebrew GCC 10.2.0_4) 10.2.0
CNL version - f902baac060f15b8c382bfc0a5594a76b187dd47 (current development HEAD)

**Additional question:**
Is there a version of to_rep which returns the underlying integer representation with correct type instead of it wrapped in cnl::_impl::wrapper? Thus the mandatory cast in code above.

**Comment by johnmcfarlane** [comment] 2021-04-08 09:36
16 represents digits, not width. It is meant to avoid confusion for those who aren't savvy with peculiarities of signed integers.

Note, elastic integer and wide integer may experience a shakeup soon based on feedback from Cologne, which might clear up some of the potential for confusion.

**Comment by hbe72** [comment] 2021-04-08 10:36
I find this confusing as the first number should represent the width of the datatype to be consistent with signed and unsigned integers.

Everybody understand the difference between uint16_t and int16_t.

I would like this to be consistent with
```cpp
static constexpr auto b = cnl::scaled_integer<int16_t, cnl::power<-15>>{0.999969482421875}; //Compiles
static constexpr auto c = cnl::scaled_integer<int16_t, cnl::power<-15>>{1.0};  //Does not compile
```

In 2's complement representation of a signed integer the first bit is sig bit and that should be generally understood.

**Comment by hbe72** [comment] 2021-04-09 20:13
I have to think about this. Btw. that link to P0828  does not work.

That Q fixed-point notation is very familiar to quite a many DSP and ASIC/ASIP guys out there. However, that is not officially standardized notation and at least two conventions of using that notation. My personal preference towards Qm+n, where m+n add up to register size, thus including the sign bit. 

I was not aware of numeric_limits::digits, so that is tip of the scale towards current implementation.

I was actually very surprised to stumble on this as I've been tinkering with CNL already a while.

**Comment by johnmcfarlane** [comment] 2021-04-12 21:01
Closing this as 'by design'. Feel free to re-open or continue the conversation though.

**Closed by johnmcfarlane** 2021-04-12 21:01 UTC
Labels: bug
